// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/webhooks/customers/data_request": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/webhooks/customers/create": {
    params: {};
  };
  "/webhooks/customers/redact": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/webhooks/orders/paid": {
    params: {};
  };
  "/webhooks/shop/redact": {
    params: {};
  };
  "/super-admin": {
    params: {};
  };
  "/super-admin/login": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
  "/app/integrations": {
    params: {};
  };
  "/app/rules": {
    params: {};
  };
  "/app/additional": {
    params: {};
  };
  "/app/rules/new": {
    params: {};
  };
  "/app/settings": {
    params: {};
  };
  "/app/pricing": {
    params: {};
  };
  "/app/export": {
    params: {};
  };
  "/app/guide": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/webhooks/customers/data_request" | "/webhooks/app/scopes_update" | "/webhooks/customers/create" | "/webhooks/customers/redact" | "/webhooks/app/uninstalled" | "/webhooks/orders/paid" | "/webhooks/shop/redact" | "/super-admin" | "/super-admin/login" | "/auth/login" | "/auth/*" | "/app" | "/app/integrations" | "/app/rules" | "/app/additional" | "/app/rules/new" | "/app/settings" | "/app/pricing" | "/app/export" | "/app/guide";
  };
  "routes/webhooks.customers.data_request.tsx": {
    id: "routes/webhooks.customers.data_request";
    page: "/webhooks/customers/data_request";
  };
  "routes/webhooks.app.scopes_update.tsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/webhooks.customers.create.tsx": {
    id: "routes/webhooks.customers.create";
    page: "/webhooks/customers/create";
  };
  "routes/webhooks.customers.redact.tsx": {
    id: "routes/webhooks.customers.redact";
    page: "/webhooks/customers/redact";
  };
  "routes/webhooks.app.uninstalled.tsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/webhooks.orders.paid.tsx": {
    id: "routes/webhooks.orders.paid";
    page: "/webhooks/orders/paid";
  };
  "routes/webhooks.shop.redact.tsx": {
    id: "routes/webhooks.shop.redact";
    page: "/webhooks/shop/redact";
  };
  "routes/super-admin.tsx": {
    id: "routes/super-admin";
    page: "/super-admin" | "/super-admin/login";
  };
  "routes/super-admin._index.tsx": {
    id: "routes/super-admin._index";
    page: "/super-admin";
  };
  "routes/super-admin.login.tsx": {
    id: "routes/super-admin.login";
    page: "/super-admin/login";
  };
  "routes/auth.login/route.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/_index/route.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.$.tsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app" | "/app/integrations" | "/app/rules" | "/app/additional" | "/app/rules/new" | "/app/settings" | "/app/pricing" | "/app/export" | "/app/guide";
  };
  "routes/app.integrations.tsx": {
    id: "routes/app.integrations";
    page: "/app/integrations";
  };
  "routes/app.rules._index.tsx": {
    id: "routes/app.rules._index";
    page: "/app/rules";
  };
  "routes/app.additional.tsx": {
    id: "routes/app.additional";
    page: "/app/additional";
  };
  "routes/app.rules.new.tsx": {
    id: "routes/app.rules.new";
    page: "/app/rules/new";
  };
  "routes/app.settings.tsx": {
    id: "routes/app.settings";
    page: "/app/settings";
  };
  "routes/app.pricing.tsx": {
    id: "routes/app.pricing";
    page: "/app/pricing";
  };
  "routes/app._index.tsx": {
    id: "routes/app._index";
    page: "/app";
  };
  "routes/app.export.tsx": {
    id: "routes/app.export";
    page: "/app/export";
  };
  "routes/app.guide.tsx": {
    id: "routes/app.guide";
    page: "/app/guide";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/webhooks.customers.data_request": typeof import("./app/routes/webhooks.customers.data_request.tsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.tsx");
  "routes/webhooks.customers.create": typeof import("./app/routes/webhooks.customers.create.tsx");
  "routes/webhooks.customers.redact": typeof import("./app/routes/webhooks.customers.redact.tsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.tsx");
  "routes/webhooks.orders.paid": typeof import("./app/routes/webhooks.orders.paid.tsx");
  "routes/webhooks.shop.redact": typeof import("./app/routes/webhooks.shop.redact.tsx");
  "routes/super-admin": typeof import("./app/routes/super-admin.tsx");
  "routes/super-admin._index": typeof import("./app/routes/super-admin._index.tsx");
  "routes/super-admin.login": typeof import("./app/routes/super-admin.login.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.tsx");
  "routes/_index": typeof import("./app/routes/_index/route.tsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.tsx");
  "routes/app": typeof import("./app/routes/app.tsx");
  "routes/app.integrations": typeof import("./app/routes/app.integrations.tsx");
  "routes/app.rules._index": typeof import("./app/routes/app.rules._index.tsx");
  "routes/app.additional": typeof import("./app/routes/app.additional.tsx");
  "routes/app.rules.new": typeof import("./app/routes/app.rules.new.tsx");
  "routes/app.settings": typeof import("./app/routes/app.settings.tsx");
  "routes/app.pricing": typeof import("./app/routes/app.pricing.tsx");
  "routes/app._index": typeof import("./app/routes/app._index.tsx");
  "routes/app.export": typeof import("./app/routes/app.export.tsx");
  "routes/app.guide": typeof import("./app/routes/app.guide.tsx");
};