import { useState, useEffect } from "react";
import { authenticate } from "../shopify.server";
import { getCachedStore } from "../services/cache.server";
import db from "../db.server";
import type { LoaderFunctionArgs, ActionFunctionArgs } from "react-router";
import { useLoaderData, useSubmit, useActionData, useNavigation, useNavigate, redirect } from "react-router";
import { useAppBridge } from "@shopify/app-bridge-react";
import { Page, Layout, Card, FormLayout, TextField, Select, Button, Banner, BlockStack, Text, InlineStack, Box, Divider, Icon, Badge } from "@shopify/polaris";
import { CashDollarIcon, PersonIcon, ClockIcon, SearchIcon, MagicIcon, CheckIcon } from "@shopify/polaris-icons";

export const loader = async ({ request }: LoaderFunctionArgs) => {
    const { session } = await authenticate.admin(request);
    const store = await getCachedStore(session.shop);
    if (!store) {
        return { planName: "Free" };
    }
    return { planName: store.planName || "Free" };
};

export const action = async ({ request }: ActionFunctionArgs) => {
    const { session } = await authenticate.admin(request);
    const shop = session.shop;

    const store = await getCachedStore(shop);
    if (!store) {
        return { error: "Store not found" };
    }

    const { admin } = await authenticate.admin(request);

    const formData = await request.formData();
    const name = formData.get("name") as string;
    const ruleType = formData.get("ruleType") as string;
    const field = formData.get("field") as string;
    const operator = formData.get("operator") as string;
    const value = formData.get("value") as string;
    const targetTag = formData.get("targetTag") as string;
    const collectionId = formData.get("collectionId") as string;
    const collectionName = formData.get("collectionName") as string;

    if (!name || !targetTag) {
        return { error: "Name and Target Tag are required" };
    }

    if (ruleType === "metric" && (!field || !operator || !value)) {
        return { error: "All metric condition fields are required" };
    }

    if (ruleType === "collection" && (!collectionId || !collectionName)) {
        return { error: "Collection ID and Name are required" };
    }

    let conditions: any[] = [];
    let description = "";

    if (ruleType === "metric") {
        let conditionValue: any = value;
        if (field !== 'lastOrderDate') {
            conditionValue = Number(value);
        }
        conditions = [{ field, operator, value: conditionValue }];
        description = `Auto-generated by UI: ${field} ${operator} ${conditionValue}`;
    } else {
        description = `Purchases from collection: ${collectionName}`;
    }

    await db.rule.create({
        data: {
            storeId: store.id,
            name,
            description,
            conditions: JSON.stringify(conditions),
            targetTag,
            collectionId: ruleType === "collection" ? collectionId : null,
            collectionName: ruleType === "collection" ? collectionName : null,
            isActive: true
        }
    });

    // START AUTO-SYNC
    // Immediately fetch customers and dispatch them to the background worker 
    // to calculate the new rule without requiring manual merchant action.
    try {
        const isFree = store.planName === "Free" || store.planName === "";
        const fetchLimit = isFree ? 50 : 250;

        const response = await admin.graphql(
            `#graphql
              query getCustomers {
                customers(first: ${fetchLimit}) {
                  edges {
                    node {
                      id
                      email
                      firstName
                      lastName
                      amountSpent {
                        amount
                      }
                      numberOfOrders
                      tags
                    }
                  }
                }
              }
            `
        );

        const data = await response.json();
        const customersToSync = data.data?.customers?.edges || [];

        // We dynamically import `enqueueSyncJob` to avoid circular dependency trees 
        // with the loader inside webhook architectures vs frontend routing
        if (customersToSync.length > 0) {
            const { enqueueSyncJob } = await import("../services/queue.server");
            enqueueSyncJob({
                shop,
                storeId: store.id,
                customersToSync
            });
        }
    } catch (e) {
        console.error("Failed to enqueue auto-sync on rule creation.", e);
    }

    return redirect("/app");
};

export default function NewRule() {
    const { planName } = useLoaderData<typeof loader>();
    const actionData = useActionData<typeof action>();
    const submit = useSubmit();
    const navigation = useNavigation();
    const navigate = useNavigate();
    const shopify = useAppBridge();
    const isSubmitting = navigation.state === "submitting";

    const isFreePlan = planName === "Free" || planName === "";

    const [name, setName] = useState("");
    const [ruleType, setRuleType] = useState("metric");
    const [field, setField] = useState("totalSpent");
    const [operator, setOperator] = useState("greaterThan");
    const [value, setValue] = useState("");
    const [collectionId, setCollectionId] = useState("");
    const [collectionName, setCollectionName] = useState("");
    const [targetTag, setTargetTag] = useState("");
    const [activePreset, setActivePreset] = useState<string | null>(null);

    const handleSubmit = () => {
        const formData = new FormData();
        formData.append("name", name);
        formData.append("ruleType", ruleType);
        formData.append("field", field);
        formData.append("operator", operator);
        formData.append("value", value);
        formData.append("collectionId", collectionId);
        formData.append("collectionName", collectionName);
        formData.append("targetTag", targetTag);

        submit(formData, { method: "post" });
    };

    const applyPreset = (preset: string) => {
        setActivePreset(preset);
        setRuleType("metric");
        if (preset === "big_spender") {
            setName("The Big Spenders");
            setField("totalSpent");
            setOperator("greaterThan");
            setValue("1000");
            setTargetTag("VIP");
        } else if (preset === "loyalist") {
            setName("The Loyalists");
            setField("orderCount");
            setOperator("greaterThan");
            setValue("5");
            setTargetTag("Loyal");
        } else if (preset === "window_shopper") {
            setName("Window Shoppers");
            setField("orderCount");
            setOperator("equals");
            setValue("0");
            setTargetTag("Prospect");
        } else if (preset === "at_risk") {
            setName("At Risk VIPs");
            setField("lastOrderDate");
            setOperator("isBefore");
            const ninetyDaysAgo = new Date();
            ninetyDaysAgo.setDate(ninetyDaysAgo.getDate() - 90);
            setValue(ninetyDaysAgo.toISOString().split("T")[0]);
            setTargetTag("AtRisk");
        }
    };

    return (
        <Page
            title="Create Automation Rule"
            backAction={{ content: 'Back to Analytics', url: '/app/rules' }}
            subtitle="Define an automated behavior to automatically tag your customers."
        >
            <style>{`
                .preset-card-wrapper {
                    transition: all 0.2s ease-in-out;
                    border-radius: 8px;
                }
                .preset-card-wrapper:hover {
                    transform: translateY(-3px);
                    box-shadow: 0 8px 16px rgba(0, 0, 0, 0.08);
                }
                .preset-card-wrapper:active {
                    transform: translateY(1px);
                    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.08);
                }
            `}</style>
            <Layout>
                <Layout.Section>
                    {actionData?.error && (
                        <Banner tone="critical" title={actionData.error} />
                    )}

                    <Box paddingBlockEnd="400">
                        <Card>
                            <BlockStack gap="400">
                                <InlineStack align="start" gap="200" blockAlign="center">
                                    <Icon source={MagicIcon} tone="magic" />
                                    <Text variant="headingMd" as="h3">Popular Automations</Text>
                                </InlineStack>

                                <Text as="p" tone="subdued">Select a ready-made template or scroll down to build your own from scratch.</Text>

                                <InlineStack gap="300" wrap>
                                    {/* Big Spender Preset */}
                                    <div className="preset-card-wrapper" style={{ flex: '1 1 200px', cursor: 'pointer' }} onClick={() => applyPreset('big_spender')}>
                                        <Box padding="300" background={activePreset === 'big_spender' ? "bg-surface-magic" : "bg-surface"} borderRadius="200" borderWidth="025" borderColor={activePreset === 'big_spender' ? "border-magic" : "border"}>
                                            <BlockStack gap="200">
                                                <Icon source={CashDollarIcon} tone={activePreset === 'big_spender' ? 'magic' : 'base'} />
                                                <Text variant="headingSm" as="h6">Big Spenders</Text>
                                                <Text as="p" variant="bodySm" tone="subdued">Total Spent &gt; $1000</Text>
                                            </BlockStack>
                                        </Box>
                                    </div>

                                    {/* Loyalists Preset */}
                                    <div className="preset-card-wrapper" style={{ flex: '1 1 200px', cursor: 'pointer' }} onClick={() => applyPreset('loyalist')}>
                                        <Box padding="300" background={activePreset === 'loyalist' ? "bg-surface-magic" : "bg-surface"} borderRadius="200" borderWidth="025" borderColor={activePreset === 'loyalist' ? "border-magic" : "border"}>
                                            <BlockStack gap="200">
                                                <Icon source={PersonIcon} tone={activePreset === 'loyalist' ? 'magic' : 'base'} />
                                                <Text variant="headingSm" as="h6">Loyalists</Text>
                                                <Text as="p" variant="bodySm" tone="subdued">Orders &gt; 5</Text>
                                            </BlockStack>
                                        </Box>
                                    </div>

                                    {/* Window Shoppers */}
                                    <div className="preset-card-wrapper" style={{ flex: '1 1 200px', cursor: 'pointer' }} onClick={() => applyPreset('window_shopper')}>
                                        <Box padding="300" background={activePreset === 'window_shopper' ? "bg-surface-magic" : "bg-surface"} borderRadius="200" borderWidth="025" borderColor={activePreset === 'window_shopper' ? "border-magic" : "border"}>
                                            <BlockStack gap="200">
                                                <Icon source={SearchIcon} tone={activePreset === 'window_shopper' ? 'magic' : 'base'} />
                                                <Text variant="headingSm" as="h6">Window Shoppers</Text>
                                                <Text as="p" variant="bodySm" tone="subdued">Orders = 0</Text>
                                            </BlockStack>
                                        </Box>
                                    </div>

                                    {/* At Risk */}
                                    <div className="preset-card-wrapper" style={{ flex: '1 1 200px', cursor: 'pointer' }} onClick={() => applyPreset('at_risk')}>
                                        <Box padding="300" background={activePreset === 'at_risk' ? "bg-surface-magic" : "bg-surface"} borderRadius="200" borderWidth="025" borderColor={activePreset === 'at_risk' ? "border-magic" : "border"}>
                                            <BlockStack gap="200">
                                                <Icon source={ClockIcon} tone={activePreset === 'at_risk' ? 'magic' : 'base'} />
                                                <Text variant="headingSm" as="h6">At Risk</Text>
                                                <Text as="p" variant="bodySm" tone="subdued">No orders in 90 days</Text>
                                            </BlockStack>
                                        </Box>
                                    </div>
                                </InlineStack>
                            </BlockStack>
                        </Card>
                    </Box>

                    <Card>
                        <BlockStack gap="500">
                            <BlockStack gap="200">
                                <Text variant="headingMd" as="h3">Rule Identification</Text>
                                <TextField
                                    label="Name your rule"
                                    value={name}
                                    onChange={setName}
                                    autoComplete="off"
                                    placeholder="e.g., Summer VIPs"
                                    helpText="Used internally to identify this automation."
                                />
                            </BlockStack>

                            <Divider />

                            <BlockStack gap="200">
                                <Text variant="headingMd" as="h3">Trigger Conditions</Text>
                                <Text as="p" tone="subdued">Define when a customer qualifies for this rule.</Text>
                                <Select
                                    label="Rule Trigger Type"
                                    options={[
                                        { label: 'Customer Metric (Spent, Count, Date)', value: 'metric' },
                                        { label: isFreePlan ? 'Specific Collection Purchase (Growth+)' : 'Specific Collection Purchase', value: 'collection' }
                                    ]}
                                    value={ruleType}
                                    onChange={setRuleType}
                                />

                                {ruleType === "collection" && isFreePlan && (
                                    <Banner tone="warning" title="Upgrade Required">
                                        <Text as="p">Collection-specific auto-tagging is available on the Growth plan and above.</Text>
                                        <Box paddingBlockStart="200">
                                            <Button onClick={() => navigate('/app/pricing')}>View Plans</Button>
                                        </Box>
                                    </Banner>
                                )}

                                {ruleType === "metric" ? (
                                    <FormLayout.Group>
                                        <Select
                                            label="Customer Attribute"
                                            options={[
                                                { label: 'Total Spent ($)', value: 'totalSpent' },
                                                { label: 'Total Order Count', value: 'orderCount' },
                                                { label: 'Date of Last Order', value: 'lastOrderDate' },
                                            ]}
                                            value={field}
                                            onChange={setField}
                                        />
                                        <Select
                                            label="Operator"
                                            options={[
                                                { label: 'Greater Than (>)', value: 'greaterThan' },
                                                { label: 'Less Than (<)', value: 'lessThan' },
                                                { label: 'Equals (=)', value: 'equals' },
                                                { label: 'Is Before Date', value: 'isBefore' },
                                                { label: 'Is After Date', value: 'isAfter' },
                                            ]}
                                            value={operator}
                                            onChange={setOperator}
                                        />
                                        <TextField
                                            label={field === 'lastOrderDate' ? 'Cutoff Date (YYYY-MM-DD)' : 'Threshold Value'}
                                            value={value}
                                            onChange={setValue}
                                            autoComplete="off"
                                            type={field === 'lastOrderDate' ? 'text' : 'number'}
                                            placeholder={field === 'lastOrderDate' ? '2023-01-01' : '1000'}
                                        />
                                    </FormLayout.Group>
                                ) : (
                                    <FormLayout.Group>
                                        <TextField
                                            label="Shopify Collection Reference ID"
                                            value={collectionId}
                                            onChange={setCollectionId}
                                            autoComplete="off"
                                            helpText="Numeric ID found in your Shopify Admin Collection URL (e.g. 123456789)."
                                            placeholder="4432104928"
                                        />
                                        <TextField
                                            label="Collection Display Name"
                                            value={collectionName}
                                            onChange={setCollectionName}
                                            autoComplete="off"
                                            helpText="For your internal reference only."
                                            placeholder="Summer 2024 Inventory"
                                        />
                                    </FormLayout.Group>
                                )}
                            </BlockStack>

                            <Divider />

                            <BlockStack gap="200">
                                <Text variant="headingMd" as="h3">Action</Text>
                                <TextField
                                    label="Shopify Tag to Apply"
                                    value={targetTag}
                                    onChange={setTargetTag}
                                    autoComplete="off"
                                    placeholder="e.g., VIP"
                                    helpText="This exact tag will be attached to the customer in Shopify."
                                />
                                {targetTag && (
                                    <InlineStack gap="200" align="start" blockAlign="center">
                                        <Text as="p" variant="bodySm" tone="subdued">Preview:</Text>
                                        <Badge tone="info">{targetTag}</Badge>
                                    </InlineStack>
                                )}
                            </BlockStack>

                            <Box paddingBlockStart="200">
                                <Button
                                    size="large"
                                    variant="primary"
                                    icon={CheckIcon}
                                    onClick={handleSubmit}
                                    loading={isSubmitting}
                                    disabled={ruleType === "collection" && isFreePlan}
                                    fullWidth
                                >
                                    Launch Smart Automation
                                </Button>
                            </Box>
                        </BlockStack>
                    </Card>
                </Layout.Section>
            </Layout>
        </Page>
    );
}
